import { readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import url from "node:url"
import plugin from "#rules"
import browser from "#browser"
import rails from "#rails"
import stimulus from "#stimulus"
import turbo from "#turbo"
import { ruleSourcePathOf } from "#helpers/eslint/rule_source"
import { callbacksystemsRules } from "#internal/base_rules/callbacksystems"

const DOCUMENT_PATH = path.join(path.dirname(url.fileURLToPath(import.meta.url)), "..", "docs", "rules.md")
const PRESETS = [
  [ "/base", Object.keys(callbacksystemsRules) ],
  [ "/browser", enabledIn(browser) ],
  [ "/rails", enabledIn(rails) ],
  [ "/restrictions", [ "callbacksystems/restrictions/exports" ] ],
  [ "/stimulus", enabledIn(stimulus) ],
  [ "/turbo", enabledIn(turbo) ]
]
const HEADING = `# Rules

<!-- Generated by \`npm run docs\`. Do not edit by hand. -->

A rule's namespace is the preset that turns it on: \`stimulus/...\` comes with
\`/stimulus\`, \`browser/...\` with \`/browser\`, and so on. A rule with no namespace
comes with \`/base\`.

Each rule links to its source, where a header comment explains what it is for and
why it exists.
`
const RULE_IDS = Object.keys(plugin.rules)
const TABLE_HEADER = [ "| Rule | Preset | Fix | Description |", "|---|---|---|---|" ]
const TABLE = `${[ ...TABLE_HEADER, ...RULE_IDS.map(rowFor) ].join("\n")}\n`

export class RulesDocument {
  #path

  constructor(filePath = DOCUMENT_PATH) {
    this.#path = filePath
  }

  async write() {
    await writeFile(this.#path, this.text)
  }

  get text() {
    return `${HEADING}\n${TABLE}`
  }

  get committed() {
    return readFile(this.#path, "utf8").catch(() => null)
  }

  get misfiledByNamespace() {
    return RULE_IDS.filter((id) => presetsFor(id).join(", ") !== presetOfNamespace(id))
  }
}

if (import.meta.main) await new RulesDocument().write()

function enabledIn(preset) {
  return preset.flatMap((block) => Object.keys(block.rules ?? {}))
}

function rowFor(id) {
  const { meta } = plugin.rules[id]
  return `| ${[
    `[\`${id}\`](../${ruleSourcePathOf(id)})`,
    `\`${presetsFor(id).join("`, `")}\``,
    meta.fixable ? "yes" : "",
    tableCellOf(meta.docs.description)
  ].join(" | ")} |`
}

// A preset that restates a `/base` rule is tuning it for its stack, not shipping it, so `/base` stays the answer.
function presetsFor(id) {
  const presets = PRESETS.filter(([ , ids ]) => ids.includes(`callbacksystems/${id}`)).map(([ name ]) => name)
  return presets.includes("/base") ? [ "/base" ] : presets
}

function tableCellOf(value) {
  return value.replaceAll("|", String.raw`\|`).replaceAll(/\r?\n/gu, " ")
}

function presetOfNamespace(id) {
  return id.includes("/") ? `/${id.split("/", 1)[0]}` : "/base"
}
